version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lodash-es
    versions:
    - 4.17.15
    - 4.17.20
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@types/react"
    versions:
    - 16.9.2
